#!/usr/bin/env python

import argparse

from commands import PowerCommand, NoSuchDeviceError


def parse_args():
    parser = argparse.ArgumentParser(description='Controls Belkin Wemo Devices')
    subparsers = parser.add_subparsers(dest='cmd', help='sub-command help')
    power_subparser = subparsers.add_parser('power', aliases=['po'], help='Controls device power')
    power_subparser.add_argument('--device', required=True, help='selects the device to control')
    power_subparser.add_argument('state', choices=['on', 'off'], help='the new power state')

    return parser.parse_args()


def get_command(args):
    cmd = None
    if args.cmd == 'power' or args.cmd == 'po':
        cmd = PowerCommand(args.device, args.state)
    return cmd


def main():
    args = parse_args()
    cmd = get_command(args)
    if cmd:
        try:
            return cmd.execute()
        except NoSuchDeviceError as nsd:
            print(nsd.message)
            return 1
        except Exception as ex:
            print(ex)
            return 1
    else:
        print("No such command: " + args.cmd)
        return 1


if __name__ == "__main__":
    main()

